import groovy.json.JsonOutput
 
pipeline {
    
    agent  {
		label 'windows_slave'
    }
 
 
 
    options{
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '10', numToKeepStr: '20'))
        timestamps()
        timeout time:30, unit:'MINUTES'
    }  
 
    
    
    environment {        
        zone="dc"
        SEEKER_PROJECT_KEY="default"

        dc_uat_ip_13='10.11.98.11'
        dc_uat_ip_14='10.11.98.12'
        dr_uat_ip_13='10.11.226.11'
        dr_uat_ip_14='10.11.226.12'
 
	    dc_pro_ip_13='10.11.42.11'
        dc_pro_ip_12='10.11.42.12'
        dr_pro_ip_13='10.11.170.11'
        dr_pro_ip_14='10.11.170.12'
    }
 
    stages {
 
        stage('Build') {
            steps {
                
                //if dir exist and files
                echo 'Building the application...'

                 script {

                        if(env.BRANCH_NAME == 'release/uat')
                        { 
                            bat "${tool 'MSBuild17'} apigee.sms.biz.sln /t:apigee_sms_biz /t:clean /t:build /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=jenkins_uat_public /p:VisualStudioVersion=15.0"
                        }
				}
            }
        }

        stage('Test')
        {
            steps {
                echo "Testing"

            }
        }


		stage('Deploy Biz_DC_11')
        {
            steps {

                script {
                    if(env.BRANCH_NAME == 'release/uat')
                    {
                        try
                        {

                          echo 'Deploying the application.... 10.11.98.11'
						  
						  routeJson('dc11')

                          withCredentials([usernamePassword(credentialsId: 'CardApi', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) 
                          {
                                bat ' echo y | \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh '+ USERNAME +'@10.11.98.11 -pw '+ PASSWORD +' C:\\Users\\pyaethu.aung\\Documents\\jenkin\\cmd.bat v1 \"C:\\inetpub\\sms1536\\v1\\*" sms1536'

                                bat 'echo y | \"C:\\Program Files\\PuTTY\\pscp.exe\" -r -P 22 -pw '+PASSWORD+' apigee.sms.biz.Publish\\* '+USERNAME+'@10.11.98.11:\\inetpub\\sms1536\\v1'

                          }


                        }catch(Exception e)
                        {
						
							throw e;
                        }
                    }

                }
            }
        }
		
		stage('Deploy Biz_DC_12')
        {
            steps {

                script {
                    if(env.BRANCH_NAME == 'release/uat')
                    {
                        try
                        {

                          echo 'Deploying the application.... 10.11.98.12'
						  
						  routeJson('dc12')

                          withCredentials([usernamePassword(credentialsId: 'CardApi', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) 
                          {
                                bat ' echo y | \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh '+ USERNAME +'@10.11.98.12 -pw '+ PASSWORD +' C:\\Users\\pyaethu.aung\\Documents\\jenkin\\cmd.bat v1 \"C:\\inetpub\\sms1536\\v1\\*" sms1536'

                                bat 'echo y | \"C:\\Program Files\\PuTTY\\pscp.exe\" -r -P 22 -pw '+PASSWORD+' apigee.sms.biz.Publish\\* '+USERNAME+'@10.11.98.12:\\inetpub\\sms1536\\v1'

                          }


                        }catch(Exception e)
                        {
							bat ' \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh svc.jenkin@10.11.98.11 -pw wQ%%I2\$dH63vqhoa0 C:\\Users\\pyaethu.aung\\Documents\\jenkin\\cmd_rollback.bat v1 \"C:\\inetpub\\sms1536\\v1" sms1536'
							
							throw e;
                        }
                    }

                }
            }
        }
		
		stage('Deploy Biz_DR_11')
        {
            steps {

                script {
                    if(env.BRANCH_NAME == 'release/uat')
                    {
                        try
                        {

                          echo 'Deploying the application.... 10.11.226.11'
						  
						  routeJson('dr11')

                          withCredentials([usernamePassword(credentialsId: 'CardApi', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) 
                          {
                                bat ' echo y | \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh '+ USERNAME +'@10.11.226.11 -pw '+ PASSWORD +' C:\\Users\\hein.htet\\Documents\\jenkin\\cmd.bat v1 \"C:\\inetpub\\sms1536\\v1\\*" sms1536'

                                bat 'echo y | \"C:\\Program Files\\PuTTY\\pscp.exe\" -r -P 22 -pw '+PASSWORD+' apigee.sms.biz.Publish\\* '+USERNAME+'@10.11.226.11:\\inetpub\\sms1536\\v1'
                          }


                        }catch(Exception e)
                        {
														
							bat ' \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh svc.jenkin@10.11.98.12 -pw wQ%%I2\$dH63vqhoa0 C:\\Users\\hein.htet\\Documents\\jenkin\\cmd_rollback.bat v1 \"C:\\inetpub\\sms1536\\v1" sms1536'
							
							bat ' \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh svc.jenkin@10.11.98.11 -pw wQ%%I2\$dH63vqhoa0 C:\\Users\\hein.htet\\Documents\\jenkin\\cmd_rollback.bat v1 \"C:\\inetpub\\sms1536\\v1" sms1536'
							
							throw e;
                        }
                    }

                }
            }
        }
		
		stage('Deploy Biz_DR_12')
        {
            steps {

                script {
                    if(env.BRANCH_NAME == 'release/uat')
                    {
                        try
                        {

                          echo 'Deploying the application.... 10.11.226.12'
						  
						  routeJson('dr12')

                          withCredentials([usernamePassword(credentialsId: 'CardApi', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) 
                          {
                                bat ' echo y | \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh '+ USERNAME +'@10.11.226.12 -pw '+ PASSWORD +' C:\\Users\\hein.htet\\Documents\\jenkin\\cmd.bat v1 \"C:\\inetpub\\sms1536\\v1\\*" sms1536'

                                bat 'echo y | \"C:\\Program Files\\PuTTY\\pscp.exe\" -r -P 22 -pw '+PASSWORD+' apigee.sms.biz.Publish\\* '+USERNAME+'@10.11.226.12:\\inetpub\\sms1536\\v1'
                          }


                        }catch(Exception e)
                        {
							bat ' \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh svc.jenkin@10.11.226.11 -pw wQ%%I2\$dH63vqhoa0 C:\\Users\\hein.htet\\Documents\\jenkin\\cmd_rollback.bat v1 \"C:\\inetpub\\sms1536\\v1" sms1536'
							
							bat ' \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh svc.jenkin@10.11.98.12 -pw wQ%%I2\$dH63vqhoa0 C:\\Users\\hein.htet\\Documents\\jenkin\\cmd_rollback.bat v1 \"C:\\inetpub\\sms1536\\v1" sms1536'
							
							bat ' \"C:\\Program Files\\PuTTY\\plink.exe\" -batch -ssh svc.jenkin@10.11.98.11 -pw wQ%%I2\$dH63vqhoa0 C:\\Users\\hein.htet\\Documents\\jenkin\\cmd_rollback.bat v1 \"C:\\inetpub\\sms1536\\v1" sms1536'
							
							throw e;
                        }
                    }

                }
            }
        }
	}
	
	post
    {
        always
        {
            cleanWs()
            deleteDir()
        }
 
        success{
            script {
                if(env.BRANCH_NAME == 'release/uat')
                {
                    echo "========success========"
                    Sendhangout("${JOB_NAME}-${BUILD_NUMBER} build is ${currentBuild.result} and took ${currentBuild.durationString.replace(' and counting', '')}");
                }
            }
        }
 
        failure{
            script{
                if(env.BRANCH_NAME == 'release/uat')
                {
                    echo "========faliure========"
                    Sendhangout("${JOB_NAME}-${BUILD_NUMBER} build is ${currentBuild.result} and took ${currentBuild.durationString.replace(' and counting', '')}");
                }   
            }
            
 
        }
    }
}

def Sendhangout(text)
{    
    def chatURL = "https://chat.googleapis.com/v1/spaces/AAAALmkpwtc/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=FyeyftZCvSuibTfa1ANDJQVYNySmCdQDi2VvPYtyuvk%%3D"

    def payload = JsonOutput.toJson([text : text]).replace("\"", "\\\"");
    
    bat "\"D:\\Program Files (x86)\\curl\\bin\\curl.exe\" --location --request POST \"${chatURL}\" --header \"Content-Type: application/json \" --data-raw  \"${payload}\"  " 
    // bat "curl --location --request"
}

def routeJson(zone)
{
    if(zone=='dr11'){
        bat 'del /f C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz.Publish\\App_Data\\kbzsms_config.json'
        bat 'copy C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz\\App_Data\\dr_11_kbzsms_config.json C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz.Publish\\App_Data\\kbzsms_config.json'
    }else if(zone == 'dr12'){
        bat 'del /f C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz.Publish\\App_Data\\kbzsms_config.json'
        bat 'copy C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz\\App_Data\\dr_12_kbzsms_config.json C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz.Publish\\App_Data\\kbzsms_config.json'
    }else if(zone == 'dc11'){
        bat 'del /f C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz.Publish\\App_Data\\kbzsms_config.json'
        bat 'copy C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz\\App_Data\\dc_11_kbzsms_config.json C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz.Publish\\App_Data\\kbzsms_config.json'
    }else{
        bat 'del /f C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz.Publish\\App_Data\\kbzsms_config.json'
        bat 'copy C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz\\App_Data\\dc_12_kbzsms_config.json C:\\jenkins\\workspace\\apigee.sms.biz_release_uat\\apigee.sms.biz.Publish\\App_Data\\kbzsms_config.json'
    }

}